apiVersion: v1
kind: Service
metadata:
  name: palestine-svc

spec:
  type: NodePort
  selector:
    app: palestine-pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080