apiVersion: v1
kind: Service
metadata:
  name: palestine-svc
  namespace: palestine-ns

spec:
  type: NodePort
  selector:
    free: palestine
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30070


---

apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: palestine-ns

spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080