name: CI (Test And Build)

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: List files
      run: ls -lah

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tester.py

  build:
    runs-on: ubuntu-latest
    needs: tester

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t palestine:latest .
